### ISSUE TITLE
http://flask.pocoo.org/docs/flask-docs.pdf shows error 

### ISSUE THREAD

**Issue by auvipy** [pallets/flask-website#16] opened 2014-12-03 11:50 UTC

**Comment by cldershem** [comment] 2015-10-24 08:12
This is a duplicate of #17.

**Comment by davidism** [comment] 2016-01-27 17:54
See mitsuhiko/flask-sqlalchemy#209, the docs are built but not moved to the expected location on the server.  http://flask.pocoo.org/docs/0.10/.latex/Flask.pdf

Fixed in 763ddeb2ac1d3478c1262e51b7c729ac3817b0f4

**Closed as completed by davidism** 2016-01-27 17:54 UTC

**Comment by zlolik** [comment] 2017-09-24 07:26
Again 404
