### ISSUE TITLE
Flask's PDF Documentation link is broken (Giving 404)

### ISSUE THREAD

**Issue by captswag** [pallets/flask-website#50] opened 2017-07-19 13:25 UTC
Hi, I tried downloading Flask's PDF documentation. The link is broken and is giving 404.
![image](https://user-images.githubusercontent.com/7058705/28368970-c270bbb2-6cb3-11e7-841e-3f110ea256cb.png)

**Comment by davidism** [comment] 2017-07-19 13:40
Duplicate of https://github.com/pocoo/flask-docs/issues/3

**Closed as completed by davidism** 2017-07-19 13:41 UTC
